apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu-18.04
spec:
  source:
    blank: {}
  pvc:
    storageClassName: csi-rbd
    dataVolume:
      name: ubuntu-golden-snap
      kind: VolumeSnapshot
      apiGroup: snapshot.storage.k8s.io/v1alpha1
    # volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
