apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: centos
spec:
  source:
    blank: {}
  pvc:
    storageClassName: csi-rbd
    dataVolume:
      name: centos-golden-snap
      kind: VolumeSnapshot
      apiGroup: snapshot.storage.k8s.io/v1alpha1
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
