apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: ubuntu-golden-snap
spec:
  snapshotClassName: csi-rbdplugin-snapclass
  source:
    name: ubuntu-template
    kind: PersistentVolumeClaim
