apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: centos-golden-snap
spec:
  snapshotClassName: csi-rbdplugin-snapclass
  source:
    name: centos-template
    kind: PersistentVolumeClaim
