apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu-template
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-cloudimg-amd64.img"
  pvc:
    storageClassName: csi-rbd
    # volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
