apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: centos-template
spec:
  source:
    http:
      url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-20150628_01.qcow2.xz"
  pvc:
    storageClassName: csi-rbd
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
