apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-restful
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
spec:
  ports:
  - name: restful
    port: 8003
    protocol: TCP
    targetPort: 8003
    nodePort: 32450
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: NodePort
