apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: centosvm
  name: centosvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: centosvm
    spec:
      domain:
        devices:
          # blockMultiQueue: true
          disks:
          - name: datavolumedisk1
            disk:
              bus: virtio
          - name: cd1
            disk:
        resources:
          requests:
            memory: 2Gi
            cpu: 2
      terminationGracePeriodSeconds: 0
      volumes:
      - name: datavolumedisk1
        persistentVolumeClaim:
          claimName: centos
      - name: cd1
        cloudInitNoCloud:
          userData: |
            #cloud-config
            ssh_pwauth: True
            password: password
            chpasswd:
              expire: False
              list: |
                 root:password
