apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: ubuntuvm
  name: ubuntuvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntuvm
    spec:
      domain:
        devices:
          blockMultiQueue: true
          disks:
          - name: datavolumedisk1
            disk:
              bus: virtio
          - name: cd1
            disk:
        resources:
          requests:
            memory: 2Gi
            cpu: 2
      terminationGracePeriodSeconds: 0
      volumes:
      - name: datavolumedisk1
        dataVolume:
          name: ubuntu
      - name: cd1
        cloudInitNoCloud:
          userData: |
            #cloud-config
            users:
              - name: root
                ssh-authorized-keys:
                  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKmrBwsfCZbesEE75ZImJPNgnwzn/9Zk+O0nSTLOJQPUV+VuqrBenHMCq6NqIhLTdVhvftf0EFJVX7JpeLsGyGmkzFinE+zP40z9xOUozcYQoDGj3ibdr22mBh2nVe1RjKejRKYKJT5TS6Yn0O91f0XPVGB/y6v2gqEeEm7W/mmed15XdeWjXrlV9jaaJKbUJqGUy4srs8ynQl3nCTofAzxiX+PErNGpAKHIahg/iixeww/D7m/fwKkH/MhOtlSQVdjE5Tm6RiIbFtpfgBLtoAoq4yTe2oMCof3gtaF+Y6CvX//INh/ocUyhL0umiRIG25mKMrcqeypiQtni7kJKi7 cklliaw@edu.uwaterloo.ca
            ssh_pwauth: True
            password: password
            chpasswd:
              expire: False
              list: |
                 root:password
