apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: clear
spec:
  source:
    pvc:
      namespace: default
      name: clear-template
  pvc:
    storageClassName: csi-rbd
    # volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
